"""create auth_token table

Revision ID: 6842007c94b9
Revises: b22129a72fa2
Create Date: 2024-11-04 23:34:07.719431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6842007c94b9'
down_revision: Union[str, None] = 'b22129a72fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('valid_till', sa.DateTime(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('profile', sa.Column('ipfs_hash', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('public_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profile', ['ipfs_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'public_key')
    op.drop_column('profile', 'ipfs_hash')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
