"""add did field to profile table

Revision ID: b22129a72fa2
Revises: 005fbda6833f
Create Date: 2024-11-04 20:01:40.852823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22129a72fa2'
down_revision: Union[str, None] = '005fbda6833f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('did', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profile', ['did'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'did')
    # ### end Alembic commands ###
